My fragment
wafflestudio18-5/team7-android pull request #12
Opened 2020-12-31 05:15 UTC by veldic

my fragment에 대한 작업을 완료했습니다.  UI는 아래와 같습니다.
RecyclerView에 onScrollListener을 추가하여 pagination된 정보를 가져오는 것을 구현하였습니다. 

error handling 및 data에 대한 후작업이 필요합니다.

<img width="313" alt="Screen Shot 2020-12-31 at 2 09 27 PM" src="https://user-images.githubusercontent.com/50933769/103395522-dd3bbf00-4b71-11eb-8410-9c419d8d9cc7.png">

2021-01-01 04:25 UTC, onemonster requested changes

2021-01-01 04:25 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/ui/main/my/MyFragment.kt
> +    private var loadingPostings: Boolean = false
`viewModel`에서 관리해야 하는 항목입니다. (`view`를 모델링 하는 것이기 때문에)

2021-01-01 04:25 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/ui/main/my/MyFragment.kt
> +                myViewModel.user = it
이 부분 지워주세요. 밑에 `MyViewModel.kt`에서 해결법 알려드립니다.

2021-01-01 04:25 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/ui/main/my/MyViewModel.kt
> +    fun getUser() = userService.getUserMe()
```
fun getUser() = userSevice.getUserMe().onNext { user = it }
```
근데 `user`이 왜 필요한지 잘 모르겠습니다. 가장 좋은건 `UserRepository`를 만들어서 거기서 user을 관리해주는 것입니다.
UserRepository는 로컬 변수로 `user: UserDto?`를 갖고 있고 `getUserMe(): Single<UserDto>`를 통해 user을 끄집어 낼 수 있는데, 내부 구현이 대충
```
getUserMe(): Single<UserDto> {
    return user?.let { Single.just(it) } ?: userService.getUserMe()
}
```

2021-01-03 12:32 UTC, veldic commented on app/src/main/java/com/wafflestudio/written/ui/main/my/MyViewModel.kt
> +    fun getUser() = userService.getUserMe()
이 Repository는 service처럼 새롭게 repository 패키지를 만들어서 구현하면 되는건가요?

2021-01-06 14:55 UTC, onemonster approved these changes
:LGTM:

2021-01-06 14:55 UTC, merged

2021-01-06 14:59 UTC, veldic commented
![](https://github.trello.services/images/mini-trello-icon.png) [MyFragment](https://trello.com/c/GLoGmTIm/10-myfragment)