Initiate Dagger
wafflestudio18-5/team7-android pull request #3
Opened 2020-12-22 09:19 UTC by veldic

Dagger로 구조를 어떻게 짜야하는지 아직은 크게 감이 안와서 일단은 구조는 짜놨는데 아마 한 번 크게 수정해야 할 듯

2020-12-22 10:03 UTC, onemonster requested changes

2020-12-22 10:03 UTC, onemonster commented on app/build.gradle
> +    def dagger_version = "2.27"
버전은 /build.gradle에 정의해주세요

2020-12-22 10:03 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/MainActivity.kt
> +    lateinit var mainViewModel: MainViewModel
https://github.com/wafflestudio/rookies/tree/master/android/lecture5/TwoTypeRecycler

이걸 참고하세요. ViewModel은 Activity에 직접 inject하면 안 됩니다. 그러면 ViewModel이 갖고 있는 성분들이 사라져요. Activity와 별개의 Lifecycle을 갖지 못합니다.

2020-12-22 10:03 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/WrittenApplication.kt
> +class WrittenApplication : Application() {
이미 유빈이가 `App : Application`을 만들었습니다. main 브랜치 풀 받고 작업해주세요.

2020-12-22 10:03 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/di/NetworkModule.kt
> +            .addConverterFactory(GsonConverterFactory.create())
`Moshi`를 썼으면 합니다. 

https://github.com/wafflestudio/rookies/tree/master/android/lecture5/TwoTypeRecycler

참고해주세요.

2020-12-22 10:31 UTC, veldic commented on app/src/main/java/com/wafflestudio/written/WrittenApplication.kt
> +class WrittenApplication : Application() {
이름이 생각했던 것이랑 달라서 착각했네요. 풀 받고 작업중입니다!

2020-12-22 11:24 UTC, onemonster approved these changes
LGTM

2020-12-22 11:25 UTC, merged

2020-12-24 05:18 UTC, veldic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dagger Hilt](https://trello.com/c/fuye2oWP/3-dagger-hilt)