Add Service DI and complete UserService with Dtos
wafflestudio18-5/team7-android pull request #6
Opened 2020-12-24 08:18 UTC by veldic

Network Module에 UserService, PostingService DI 추가

models에 UserDto, PostingDto 추가
UserService에 백엔드 `API User`에 있던 기능 모두 추가

2020-12-24 08:30 UTC, onemonster requested changes

2020-12-24 08:30 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/dto/user/UserLoginResponse.kt
> +data class UserLoginResponse(
`data class UserResponse()`로 통일합시다. `access_token`도 camelCase로 바꾸는 방법이 있습니다.
```
@field:Json("access_token")
val accessToken: String
```
그리고 무조건 반환되는 값들이라 ? 빼는게 맞습니다.

2020-12-24 08:30 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/UserService.kt
> +interface UserService {
service랑 retrofit service 구분합시다. 세미나 5번의 ToDo 예제 참조하세요.

2020-12-24 08:30 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/di/NetworkModule.kt
>  }
파일 끝에 엔터 한번 쳐줍시다.

2020-12-24 08:30 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/UserService.kt
> +        @Path("user_id") user_id: String = ""
default 값은 service단에서 넣고 retrofit service단에서는 default 주지 맙시다.

2020-12-24 08:30 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/dto/user/UserUpdateInfoRequest.kt
> +data class UserUpdateInfoRequest(
`UserInfoUpdateRequest`가 어순이 더 맞는것 같습니다. 아니면 그냥  `UserUpdateRequest`

2020-12-24 09:07 UTC, onemonster requested changes

2020-12-24 09:07 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/service/UserService.kt
> +    fun getUserById(userId: Int = 0) = userRetrofitService.getUserById(userId.toString())
id = 0인 유저는 없습니다. 실은 이 파일에 있는 디폴트 값들 중에 page_size제외하곤 필요 없습니다.

2020-12-24 09:07 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/service/UserService.kt
> +        cursor: Int = 0,
cursor은 String? 이어야 합니다.

2020-12-24 09:07 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/service/retrofit/UserRetrofitService.kt
> +        @Path("user_id") user_id: String
Kotlin 진영에서는 camelCase를 써주세요. (이 파일 전체)

2020-12-24 09:07 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/MainViewModel.kt
> +import com.wafflestudio.written.network.service.TempService
TempService 지운거 아닌가요?

2020-12-24 09:15 UTC, veldic commented on app/src/main/java/com/wafflestudio/written/MainViewModel.kt
> +import com.wafflestudio.written.network.service.TempService
TempService 아직 안지웠어요

2020-12-24 09:19 UTC, onemonster requested changes
`@field:Json` 적용 왜 안 하나요 ㅠㅠ

2020-12-24 09:19 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/models/PostingDto.kt
> +    val created_at: String
CamelCase

2020-12-24 09:19 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/models/UserDto.kt
> +    val first_posted_at: String
CamelCase

2020-12-24 09:19 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/dto/user/UserLoginResponse.kt
> +    val access_token: String
CamelCase

2020-12-24 09:19 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/dto/user/UserSignUpResponse.kt
> +    val access_token: String
CamelCase

2020-12-24 09:19 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/service/UserService.kt
> +    fun getUserById(userId: Int = 0) = userRetrofitService.getUserById(userId.toString())
그 해결 안 하신 다음에 resolve 누르시면 안 됩니다...

2020-12-24 10:25 UTC, onemonster approved these changes
두개만 고치고 머지합시다 ㅎ

2020-12-24 10:25 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/service/retrofit/UserRetrofitService.kt
> +        @Query("cursor") cursor: String,
여기도 `String?`이어야 합니다

2020-12-24 10:25 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/network/service/UserService.kt
> +        cursor.orEmpty(),
그대로 넘깁시다.

2020-12-24 11:09 UTC, merged

2020-12-25 02:50 UTC, veldic commented
![](https://github.trello.services/images/mini-trello-icon.png) [UserService + Data Class](https://trello.com/c/u2xQfAmg/17-userservice-data-class)