splash activity (incomplete) & menu (complete)
wafflestudio18-5/team7-android pull request #9
Opened 2020-12-26 03:45 UTC by yblee2001

2020-12-26 03:46 UTC, yblee2001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [MainActivity: Menu](https://trello.com/c/iBtTZo7C/14-mainactivity-menu)

2020-12-26 05:07 UTC, onemonster requested changes

2020-12-26 05:07 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/ui/main/MainActivity.kt
> +                addToBackStack("name")
이 부분이 필요한가요?

2020-12-26 05:07 UTC, onemonster commented on app/src/main/java/com/wafflestudio/written/ui/splash/SplashActivity.kt
> +        binding = ActivitySplashBinding.inflate(layoutInflater)
Splash 화면은 xml이 필요없습니다.

2020-12-26 05:07 UTC, onemonster commented on app/src/main/res/font/fonts.xml
> +        android:fontStyle="normal"
fontStyle이 겹치면 안 됩니다. 여기에 "bold"로 바꿔주세요

2020-12-28 05:44 UTC, onemonster approved these changes
LGTM

2020-12-28 08:26 UTC, merged